apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaduxjt1428-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaduxjt1428-tenant-component
    app.kubernetes.io/part-of: loaduxjt1428-tenant-app
  name: loaduxjt1428-tenant-component
  namespace: loaduxjt1428-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loaduxjt1428-tenant-component
    weight: null
status: {}
